-- Members of Congress who have filed STOCK Act disclosures.
CREATE TABLE members (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    chamber   VARCHAR(20),
    party     VARCHAR(50),
    state     VARCHAR(50),
    CONSTRAINT uq_members_full_name UNIQUE (full_name)
);

CREATE INDEX idx_members_chamber ON members (chamber);
