-- Disclosed congressional trades. source_filing_id is unique so ingestion is
-- idempotent (re-runs update rather than duplicate).
CREATE TABLE trades (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id         BIGINT NOT NULL,
    ticker            VARCHAR(32) NOT NULL,
    asset_description VARCHAR(512),
    transaction_type  VARCHAR(20),
    amount_range_low  NUMERIC(19, 2),
    amount_range_high NUMERIC(19, 2),
    transaction_date  DATE,
    disclosure_date   DATE,
    days_to_disclose  INTEGER,
    source_filing_id  VARCHAR(255),
    CONSTRAINT fk_trades_member FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT uq_trades_source_filing_id UNIQUE (source_filing_id)
);

CREATE INDEX idx_trades_ticker ON trades (ticker);
CREATE INDEX idx_trades_member ON trades (member_id);
CREATE INDEX idx_trades_transaction_date ON trades (transaction_date);
