-- Detected research-only patterns across one or more trades.
CREATE TABLE signals (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_type       VARCHAR(30) NOT NULL,
    ticker            VARCHAR(32),
    description       VARCHAR(1024),
    detected_at       TIMESTAMP,
    related_trade_ids VARCHAR(512),
    score             DOUBLE PRECISION
);

CREATE INDEX idx_signals_ticker ON signals (ticker);
CREATE INDEX idx_signals_type ON signals (signal_type);
