-- Tickers the ingestion job tracks. A handful of widely-held, frequently-traded
-- names used by members of Congress, seeded so the app is useful out of the box.
CREATE TABLE watchlist (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(32) NOT NULL,
    label  VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_watchlist_ticker UNIQUE (ticker)
);

INSERT INTO watchlist (ticker, label, active) VALUES
    ('AAPL', 'Apple Inc.',            TRUE),
    ('MSFT', 'Microsoft Corp.',       TRUE),
    ('NVDA', 'NVIDIA Corp.',          TRUE),
    ('AMZN', 'Amazon.com Inc.',       TRUE),
    ('GOOGL','Alphabet Inc.',         TRUE),
    ('META', 'Meta Platforms Inc.',   TRUE),
    ('TSLA', 'Tesla Inc.',            TRUE),
    ('JPM',  'JPMorgan Chase & Co.',  TRUE),
    ('XOM',  'Exxon Mobil Corp.',     TRUE),
    ('LMT',  'Lockheed Martin Corp.', TRUE);
